fail_fast: false

repos:
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=127]
        exclude: ^build/

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        # args: [--ignore=F401,E266,E203,--max-line-length=127]
        args: ["--ignore=F401,E266,E203", "--max-line-length=127"]
        exclude: ^build/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--line-length=127]
        exclude: ^(build/|tests/)
